### ISSUE TITLE
Models and Tables

### ISSUE THREAD

**Issue by david-at-ocs** [david-at-ocs/06-23-beer-ratings#10]
![screen shot 2015-06-23 at 3 06 06 pm](https://cloud.githubusercontent.com/assets/11997143/8315954/877fe518-19b9-11e5-8964-b20cf797b7fc.png)

**Comment by sumeetjain** [comment]
- [x] User/Rating is not a many-to-many, so these lines (http://cl.ly/bkfC/Screen%20Shot%202015-06-23%20at%203.00.40%20PM.png) are incorrect.
- [x] Same with Beer/Rating

Otherwise, :+1: :rocket:
